### ISSUE TITLE
is there a way to make it use more refs?

### ISSUE THREAD

**Issue by jeffalo** [scambier/markov-strings#14]
hello! i really like this package, and there just isn't anything like it. :)

is there any way to force the generator to use more refs? i'm giving it a lot of input (thousands) but the output seems to usually be made with single digit amounts of refs. 

i'm using a filter to use more than the minimum amounts of refs, but it takes forever to generate and it's not very performant.

perhaps i'm misunderstanding how markov chains work, but is there a way to make it use more refs? or atleast generate more interesting output?

**Comment by scambier** [comment]
Hello :)

The way it works it quite simple: each sentence of your corpus is deconstructed in chunks of 2 words (by default).  
"_I am generating markov chains_" becomes `[i, am], [am, generating], [generating, markov], [markov, chains]`

The generator picks a random chunk that can begin a sentence (`[i, am]`), look at its last word (`"am"`) and then will try to find another chunk that begins with this word. It repeats the process with non-starting chunks until the last one can end the sentence, and the `filter()` callback (if any) is satisfied.

> i'm using a filter to use more than the minimum amounts of refs, but it takes forever to generate and it's not very performant.

It takes forever because it's trying again and again until your minimal amount of refs is satisfied. The generator does not know where it's going, it just picks random chunks until it finds one that can end a sentence. The filter does not influence the generation process, it just rejects outputs that do not meet its requirements.

> is there any way to force the generator to use more refs?

Why do you want more refs exactly? From my experience 3 or 4 refs are often enough to get a good result.

What you can do instead is requiring a minimum `score`, or a minimum `score / number of refs`. The score is a relative value based on the number of possible permutations. Higher is "better", but the actual value depends on your corpus. It's IMO a more useful metric than the number of refs.

**Comment by jeffalo** [comment]
ah! thank you so much for explaining all this, i'll experiment with the score to see what i can get :)

**Comment by scambier** [comment]
You're welcome. A trick I've also used in the past is to use [string-similarity](https://www.npmjs.com/package/string-similarity) to simply check that my output wasn't too similar to any of my inputs. I don't know how it would scale with your corpus' volume.
