### ISSUE TITLE
Very short / 1-ref sentences

### ISSUE THREAD

**Issue by old-df38257622** [scambier/markov-strings#8]
Hey all. I'm using a ~142kb (at the time of writing, always growing, user generated) data file, an array of objects formatted like this:<br>
`{string: 'text text etc..', author: 'userid..', ?at: 'timestamp..'}`<br>
I have maxTries set to 50, and even with only 1 or 2 states, every sentence comes out something like this:<br>
`{
  string: 'The frog has something',
  score: 0,
  refs: [
    { string: 'The frog has something', author: '556614860931072012' }
  ],
  tries: 1
}`<br>
Only one try, and either 1-2 sentences or a verbatim copy of the one ref. Any idea why this happens? Thanks!

**Comment by scambier** [comment]
Hello!
Since your result is generated after a single try, increasing `maxTries` won't help you; it's only useful when `.generate()` does _not_ successfully produce an output.

Instead, you can take advantage of the `filter` callback, like this:
```ts
// Make sure that you have a minimal score
const sentence = markov.generate({
  filter: result => result.score > 10
})

// Or that your sentences at least have multiple references
const sentence = markov.generate({
  filter: result => result.refs.length > 1
})
```
Do note that the `score` value is entirely relative to your corpus, so it takes a bit of trial and error to figure out a good value.

If that fails, would you mind sharing your data file (even privately?), so that I can experiment with it?

**Comment by old-df38257622** [comment]
Hey! Thanks a ton for this answer, this is very helpful. I've got much better looking chains now, using multiple refs and looking more like I want them to. Problem solved :)
